### ISSUE TITLE
Portmaster reports more free space 1 card setup

### ISSUE THREAD

**Issue by roo1234** [AeolusUX/ArkOS-R3XS#44]
And goes on to corrupt the files when installing Ports.
This is a follow up of #42, it was solved by reinstalling (re-copying) it in tools. Portmaster was able to run.
However I still run into that problem that I hoped would fix in new ArkOS and PortMaster versions. 
In one card setup only, Portmaster reports wrong free space (much more than real) and corrupts files when installing anything in easyroms partition.
I opened this in portmaster discord issues but they say it just unzips the files.
So I guess this must be some OS problem. Have tried different card brands and they are initially consistent (CHKDSK, disk Genius etc).

**Comment by AeolusUX** [comment]
iirc portmaster just queries the device of its free space using df, it could be something on your sd card or the microsdcard controller of these devices hence cannot be fixed by software, or would need a more extensive study (atleast need to replicate it on similar hardware) with which I don't have time to do. I suggest just replacing the cards to ones that work with no issues.
