### ISSUE TITLE
README doesn't match latest release

### ISSUE THREAD

**Issue by r0ckarong** [AeolusUX/ArkOS-R3XS#64]
If you happen upon the github page of this project you would expect to see the latest information. The latest release info contains different links to the artifacts and some of the info would be crucial to flash the right image.

Please if you fashion a new release: Trigger a release on GitHub.

If you have the time, give us an idea of what you did. The overall "Changelogs" is pointless because it can't  give me an -incremental- change to what you did before.

I have a bunch of R36s that I want to work fine. This image just can't and shouldn't break. I don't want to stay "2022/23" ....

WiFi finally works. Let US GO!

**Comment by AeolusUX** [comment]
Oh yeah you're right I haven't been able to replace the readme for this latest release thanks for pointing that out. 

Regarding the changelogs usually the changes are the same as the changes from the official with or without additional changes given by the community or made for only the R3XS devices. They might look the same because they are but there are some additional on the R3XS changelog themselves. I'm thinking about maybe adding them on the releases as well since I started uploading the files themselves on the release so maybe I'll do that for next changelog.
